package com.example.tlunet.extensions


     const val errLogin: String = "Tài khoản hoặc mật khẩu không chính xác"
     const val errCode: String = "400"
     const val errStatus: String = "error"
     const val successCode: String = "200"
     const val successStatus: String = "success"
     const val categories: String = "categories"
     const val users: String = "users"
     const val comments: String = "comments"
     const val documents: String = "documents"
     const val subjects: String = "subjects"
     const val name: String = "name"
     const val code: String = "code"
     const val subjectCode: String = "subjectCode"
     const val categoriesCode: String = "categoriesCode"
     const val titleNav: String = "titleNav"
     const val CNTT: String = "CNTT"
     const val cnttName: String = "Công nghệ thông tin"
     const val KT: String = "KT"
     const val ktName: String = "Kinh tế"
     const val KTCK: String = "KTCK"
     const val ktckName: String = "Cơ khí"


     const val authorKey: String = "author"
     const val contentKey: String = "content"
     const val createAtKey: String = "createAt"
     const val emailKey: String = "email"
     const val documentUrlKey: String = "documentUrl"
     const val optionSubjectKey: String = "optionSubject"
     const val fullnameKey: String = "fullname"
     const val roleKey: String = "role"
